name: erad
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  lottie: ^3.3.1
  path_provider: ^2.1.2
  pdf: ^3.11.3
  printing: ^5.14.2
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.12.0
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 700
